
// This file has been generated by the GUI designer. Do not modify.

public partial class MainWindow
{
	private global::Gtk.VBox vbox1;

	private global::Gtk.Label Calculadora;

	private global::Gtk.VBox vbox3;

	private global::Gtk.Entry Pantalla;

	private global::Gtk.HBox hbox5;

	private global::Gtk.Button Bvaciar;

	private global::Gtk.Button BC;

	private global::Gtk.HBox hbox4;

	private global::Gtk.Button BP;

	private global::Gtk.Button BCero;

	private global::Gtk.HBox hbox7;

	private global::Gtk.Button BI;

	private global::Gtk.Button BR;

	private global::Gtk.VBox vbox2;

	private global::Gtk.HBox hbox3;

	private global::Gtk.Button B7;

	private global::Gtk.Button B8;

	private global::Gtk.HBox hbox8;

	private global::Gtk.Button B9;

	private global::Gtk.Button BD;

	private global::Gtk.HBox hbox2;

	private global::Gtk.Button B4;

	private global::Gtk.Button B5;

	private global::Gtk.HBox hbox9;

	private global::Gtk.Button B6;

	private global::Gtk.Button BM;

	private global::Gtk.HBox hbox1;

	private global::Gtk.Button B1;

	private global::Gtk.Button B2;

	private global::Gtk.HBox hbox10;

	private global::Gtk.Button B3;

	private global::Gtk.Button BS;

	protected virtual void Build()
	{
		global::Stetic.Gui.Initialize(this);
		// Widget MainWindow
		this.Name = "MainWindow";
		this.Title = global::Mono.Unix.Catalog.GetString("MainWindow");
		this.WindowPosition = ((global::Gtk.WindowPosition)(4));
		this.BorderWidth = ((uint)(18));
		// Container child MainWindow.Gtk.Container+ContainerChild
		this.vbox1 = new global::Gtk.VBox();
		this.vbox1.Name = "vbox1";
		this.vbox1.Spacing = 6;
		// Container child vbox1.Gtk.Box+BoxChild
		this.Calculadora = new global::Gtk.Label();
		this.Calculadora.Name = "Calculadora";
		this.Calculadora.LabelProp = global::Mono.Unix.Catalog.GetString("calculadora");
		this.vbox1.Add(this.Calculadora);
		global::Gtk.Box.BoxChild w1 = ((global::Gtk.Box.BoxChild)(this.vbox1[this.Calculadora]));
		w1.Position = 0;
		w1.Expand = false;
		w1.Fill = false;
		// Container child vbox1.Gtk.Box+BoxChild
		this.vbox3 = new global::Gtk.VBox();
		this.vbox3.Name = "vbox3";
		this.vbox3.Spacing = 6;
		// Container child vbox3.Gtk.Box+BoxChild
		this.Pantalla = new global::Gtk.Entry();
		this.Pantalla.CanFocus = true;
		this.Pantalla.Name = "Pantalla";
		this.Pantalla.IsEditable = false;
		this.Pantalla.InvisibleChar = '•';
		this.vbox3.Add(this.Pantalla);
		global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild)(this.vbox3[this.Pantalla]));
		w2.Position = 0;
		w2.Expand = false;
		w2.Fill = false;
		// Container child vbox3.Gtk.Box+BoxChild
		this.hbox5 = new global::Gtk.HBox();
		this.hbox5.Name = "hbox5";
		this.hbox5.Spacing = 6;
		// Container child hbox5.Gtk.Box+BoxChild
		this.Bvaciar = new global::Gtk.Button();
		this.Bvaciar.WidthRequest = 132;
		this.Bvaciar.HeightRequest = 40;
		this.Bvaciar.CanFocus = true;
		this.Bvaciar.Name = "Bvaciar";
		this.Bvaciar.UseUnderline = true;
		this.Bvaciar.Label = global::Mono.Unix.Catalog.GetString("VACIAR");
		this.hbox5.Add(this.Bvaciar);
		global::Gtk.Box.BoxChild w3 = ((global::Gtk.Box.BoxChild)(this.hbox5[this.Bvaciar]));
		w3.Position = 0;
		w3.Expand = false;
		w3.Fill = false;
		// Container child hbox5.Gtk.Box+BoxChild
		this.BC = new global::Gtk.Button();
		this.BC.WidthRequest = 40;
		this.BC.HeightRequest = 40;
		this.BC.CanFocus = true;
		this.BC.Name = "BC";
		this.BC.UseUnderline = true;
		this.BC.Label = global::Mono.Unix.Catalog.GetString("C");
		this.hbox5.Add(this.BC);
		global::Gtk.Box.BoxChild w4 = ((global::Gtk.Box.BoxChild)(this.hbox5[this.BC]));
		w4.Position = 1;
		w4.Expand = false;
		w4.Fill = false;
		this.vbox3.Add(this.hbox5);
		global::Gtk.Box.BoxChild w5 = ((global::Gtk.Box.BoxChild)(this.vbox3[this.hbox5]));
		w5.Position = 1;
		w5.Expand = false;
		w5.Fill = false;
		// Container child vbox3.Gtk.Box+BoxChild
		this.hbox4 = new global::Gtk.HBox();
		this.hbox4.Name = "hbox4";
		this.hbox4.Spacing = 6;
		// Container child hbox4.Gtk.Box+BoxChild
		this.BP = new global::Gtk.Button();
		this.BP.WidthRequest = 40;
		this.BP.HeightRequest = 40;
		this.BP.CanFocus = true;
		this.BP.Name = "BP";
		this.BP.UseUnderline = true;
		this.BP.Label = global::Mono.Unix.Catalog.GetString(".");
		this.hbox4.Add(this.BP);
		global::Gtk.Box.BoxChild w6 = ((global::Gtk.Box.BoxChild)(this.hbox4[this.BP]));
		w6.Position = 0;
		w6.Expand = false;
		w6.Fill = false;
		// Container child hbox4.Gtk.Box+BoxChild
		this.BCero = new global::Gtk.Button();
		this.BCero.WidthRequest = 40;
		this.BCero.HeightRequest = 40;
		this.BCero.CanFocus = true;
		this.BCero.Name = "BCero";
		this.BCero.UseUnderline = true;
		this.BCero.Label = global::Mono.Unix.Catalog.GetString("0");
		this.hbox4.Add(this.BCero);
		global::Gtk.Box.BoxChild w7 = ((global::Gtk.Box.BoxChild)(this.hbox4[this.BCero]));
		w7.Position = 1;
		w7.Expand = false;
		w7.Fill = false;
		// Container child hbox4.Gtk.Box+BoxChild
		this.hbox7 = new global::Gtk.HBox();
		this.hbox7.Name = "hbox7";
		this.hbox7.Spacing = 6;
		// Container child hbox7.Gtk.Box+BoxChild
		this.BI = new global::Gtk.Button();
		this.BI.WidthRequest = 40;
		this.BI.HeightRequest = 40;
		this.BI.CanFocus = true;
		this.BI.Name = "BI";
		this.BI.UseUnderline = true;
		this.BI.Label = global::Mono.Unix.Catalog.GetString("=");
		this.hbox7.Add(this.BI);
		global::Gtk.Box.BoxChild w8 = ((global::Gtk.Box.BoxChild)(this.hbox7[this.BI]));
		w8.Position = 0;
		w8.Expand = false;
		w8.Fill = false;
		// Container child hbox7.Gtk.Box+BoxChild
		this.BR = new global::Gtk.Button();
		this.BR.WidthRequest = 40;
		this.BR.HeightRequest = 40;
		this.BR.CanFocus = true;
		this.BR.Name = "BR";
		this.BR.UseUnderline = true;
		this.BR.Label = global::Mono.Unix.Catalog.GetString("-");
		this.hbox7.Add(this.BR);
		global::Gtk.Box.BoxChild w9 = ((global::Gtk.Box.BoxChild)(this.hbox7[this.BR]));
		w9.Position = 1;
		w9.Expand = false;
		w9.Fill = false;
		this.hbox4.Add(this.hbox7);
		global::Gtk.Box.BoxChild w10 = ((global::Gtk.Box.BoxChild)(this.hbox4[this.hbox7]));
		w10.Position = 2;
		w10.Expand = false;
		w10.Fill = false;
		this.vbox3.Add(this.hbox4);
		global::Gtk.Box.BoxChild w11 = ((global::Gtk.Box.BoxChild)(this.vbox3[this.hbox4]));
		w11.Position = 2;
		w11.Expand = false;
		w11.Fill = false;
		this.vbox1.Add(this.vbox3);
		global::Gtk.Box.BoxChild w12 = ((global::Gtk.Box.BoxChild)(this.vbox1[this.vbox3]));
		w12.Position = 1;
		w12.Expand = false;
		w12.Fill = false;
		// Container child vbox1.Gtk.Box+BoxChild
		this.vbox2 = new global::Gtk.VBox();
		this.vbox2.Name = "vbox2";
		this.vbox2.Spacing = 6;
		// Container child vbox2.Gtk.Box+BoxChild
		this.hbox3 = new global::Gtk.HBox();
		this.hbox3.Name = "hbox3";
		this.hbox3.Spacing = 6;
		// Container child hbox3.Gtk.Box+BoxChild
		this.B7 = new global::Gtk.Button();
		this.B7.WidthRequest = 40;
		this.B7.HeightRequest = 40;
		this.B7.CanFocus = true;
		this.B7.Name = "B7";
		this.B7.UseUnderline = true;
		this.B7.Label = global::Mono.Unix.Catalog.GetString("7");
		this.hbox3.Add(this.B7);
		global::Gtk.Box.BoxChild w13 = ((global::Gtk.Box.BoxChild)(this.hbox3[this.B7]));
		w13.Position = 0;
		w13.Expand = false;
		w13.Fill = false;
		// Container child hbox3.Gtk.Box+BoxChild
		this.B8 = new global::Gtk.Button();
		this.B8.WidthRequest = 40;
		this.B8.HeightRequest = 40;
		this.B8.CanFocus = true;
		this.B8.Name = "B8";
		this.B8.UseUnderline = true;
		this.B8.Label = global::Mono.Unix.Catalog.GetString("8");
		this.hbox3.Add(this.B8);
		global::Gtk.Box.BoxChild w14 = ((global::Gtk.Box.BoxChild)(this.hbox3[this.B8]));
		w14.Position = 1;
		w14.Expand = false;
		w14.Fill = false;
		// Container child hbox3.Gtk.Box+BoxChild
		this.hbox8 = new global::Gtk.HBox();
		this.hbox8.Name = "hbox8";
		this.hbox8.Spacing = 6;
		// Container child hbox8.Gtk.Box+BoxChild
		this.B9 = new global::Gtk.Button();
		this.B9.WidthRequest = 40;
		this.B9.HeightRequest = 40;
		this.B9.CanFocus = true;
		this.B9.Name = "B9";
		this.B9.UseUnderline = true;
		this.B9.Label = global::Mono.Unix.Catalog.GetString("9");
		this.hbox8.Add(this.B9);
		global::Gtk.Box.BoxChild w15 = ((global::Gtk.Box.BoxChild)(this.hbox8[this.B9]));
		w15.Position = 0;
		w15.Expand = false;
		w15.Fill = false;
		// Container child hbox8.Gtk.Box+BoxChild
		this.BD = new global::Gtk.Button();
		this.BD.WidthRequest = 40;
		this.BD.HeightRequest = 40;
		this.BD.CanFocus = true;
		this.BD.Name = "BD";
		this.BD.UseUnderline = true;
		this.BD.Label = global::Mono.Unix.Catalog.GetString("/");
		this.hbox8.Add(this.BD);
		global::Gtk.Box.BoxChild w16 = ((global::Gtk.Box.BoxChild)(this.hbox8[this.BD]));
		w16.Position = 1;
		w16.Expand = false;
		w16.Fill = false;
		this.hbox3.Add(this.hbox8);
		global::Gtk.Box.BoxChild w17 = ((global::Gtk.Box.BoxChild)(this.hbox3[this.hbox8]));
		w17.Position = 2;
		w17.Expand = false;
		w17.Fill = false;
		this.vbox2.Add(this.hbox3);
		global::Gtk.Box.BoxChild w18 = ((global::Gtk.Box.BoxChild)(this.vbox2[this.hbox3]));
		w18.Position = 0;
		w18.Expand = false;
		w18.Fill = false;
		// Container child vbox2.Gtk.Box+BoxChild
		this.hbox2 = new global::Gtk.HBox();
		this.hbox2.Name = "hbox2";
		this.hbox2.Spacing = 6;
		// Container child hbox2.Gtk.Box+BoxChild
		this.B4 = new global::Gtk.Button();
		this.B4.WidthRequest = 40;
		this.B4.HeightRequest = 40;
		this.B4.CanFocus = true;
		this.B4.Name = "B4";
		this.B4.UseUnderline = true;
		this.B4.Label = global::Mono.Unix.Catalog.GetString("4");
		this.hbox2.Add(this.B4);
		global::Gtk.Box.BoxChild w19 = ((global::Gtk.Box.BoxChild)(this.hbox2[this.B4]));
		w19.Position = 0;
		w19.Expand = false;
		w19.Fill = false;
		// Container child hbox2.Gtk.Box+BoxChild
		this.B5 = new global::Gtk.Button();
		this.B5.WidthRequest = 40;
		this.B5.HeightRequest = 40;
		this.B5.CanFocus = true;
		this.B5.Name = "B5";
		this.B5.UseUnderline = true;
		this.B5.Label = global::Mono.Unix.Catalog.GetString("5");
		this.hbox2.Add(this.B5);
		global::Gtk.Box.BoxChild w20 = ((global::Gtk.Box.BoxChild)(this.hbox2[this.B5]));
		w20.Position = 1;
		w20.Expand = false;
		w20.Fill = false;
		// Container child hbox2.Gtk.Box+BoxChild
		this.hbox9 = new global::Gtk.HBox();
		this.hbox9.Name = "hbox9";
		this.hbox9.Spacing = 6;
		// Container child hbox9.Gtk.Box+BoxChild
		this.B6 = new global::Gtk.Button();
		this.B6.WidthRequest = 40;
		this.B6.HeightRequest = 40;
		this.B6.CanFocus = true;
		this.B6.Name = "B6";
		this.B6.UseUnderline = true;
		this.B6.Label = global::Mono.Unix.Catalog.GetString("6");
		this.hbox9.Add(this.B6);
		global::Gtk.Box.BoxChild w21 = ((global::Gtk.Box.BoxChild)(this.hbox9[this.B6]));
		w21.Position = 0;
		w21.Expand = false;
		w21.Fill = false;
		// Container child hbox9.Gtk.Box+BoxChild
		this.BM = new global::Gtk.Button();
		this.BM.WidthRequest = 40;
		this.BM.HeightRequest = 40;
		this.BM.CanFocus = true;
		this.BM.Name = "BM";
		this.BM.UseUnderline = true;
		this.BM.Label = global::Mono.Unix.Catalog.GetString("*");
		this.hbox9.Add(this.BM);
		global::Gtk.Box.BoxChild w22 = ((global::Gtk.Box.BoxChild)(this.hbox9[this.BM]));
		w22.Position = 1;
		w22.Expand = false;
		w22.Fill = false;
		this.hbox2.Add(this.hbox9);
		global::Gtk.Box.BoxChild w23 = ((global::Gtk.Box.BoxChild)(this.hbox2[this.hbox9]));
		w23.Position = 2;
		w23.Expand = false;
		w23.Fill = false;
		this.vbox2.Add(this.hbox2);
		global::Gtk.Box.BoxChild w24 = ((global::Gtk.Box.BoxChild)(this.vbox2[this.hbox2]));
		w24.Position = 1;
		w24.Expand = false;
		w24.Fill = false;
		// Container child vbox2.Gtk.Box+BoxChild
		this.hbox1 = new global::Gtk.HBox();
		this.hbox1.Name = "hbox1";
		this.hbox1.Spacing = 6;
		// Container child hbox1.Gtk.Box+BoxChild
		this.B1 = new global::Gtk.Button();
		this.B1.WidthRequest = 40;
		this.B1.HeightRequest = 40;
		this.B1.CanFocus = true;
		this.B1.Name = "B1";
		this.B1.UseUnderline = true;
		this.B1.Label = global::Mono.Unix.Catalog.GetString("1");
		this.hbox1.Add(this.B1);
		global::Gtk.Box.BoxChild w25 = ((global::Gtk.Box.BoxChild)(this.hbox1[this.B1]));
		w25.Position = 0;
		w25.Expand = false;
		w25.Fill = false;
		// Container child hbox1.Gtk.Box+BoxChild
		this.B2 = new global::Gtk.Button();
		this.B2.WidthRequest = 40;
		this.B2.HeightRequest = 40;
		this.B2.CanFocus = true;
		this.B2.Name = "B2";
		this.B2.UseUnderline = true;
		this.B2.Label = global::Mono.Unix.Catalog.GetString("2");
		this.hbox1.Add(this.B2);
		global::Gtk.Box.BoxChild w26 = ((global::Gtk.Box.BoxChild)(this.hbox1[this.B2]));
		w26.Position = 1;
		w26.Expand = false;
		w26.Fill = false;
		// Container child hbox1.Gtk.Box+BoxChild
		this.hbox10 = new global::Gtk.HBox();
		this.hbox10.Name = "hbox10";
		this.hbox10.Spacing = 6;
		// Container child hbox10.Gtk.Box+BoxChild
		this.B3 = new global::Gtk.Button();
		this.B3.WidthRequest = 40;
		this.B3.HeightRequest = 40;
		this.B3.CanFocus = true;
		this.B3.Name = "B3";
		this.B3.UseUnderline = true;
		this.B3.Label = global::Mono.Unix.Catalog.GetString("3");
		this.hbox10.Add(this.B3);
		global::Gtk.Box.BoxChild w27 = ((global::Gtk.Box.BoxChild)(this.hbox10[this.B3]));
		w27.Position = 0;
		w27.Expand = false;
		w27.Fill = false;
		// Container child hbox10.Gtk.Box+BoxChild
		this.BS = new global::Gtk.Button();
		this.BS.WidthRequest = 40;
		this.BS.HeightRequest = 40;
		this.BS.CanFocus = true;
		this.BS.Name = "BS";
		this.BS.UseUnderline = true;
		this.BS.Label = global::Mono.Unix.Catalog.GetString("+");
		this.hbox10.Add(this.BS);
		global::Gtk.Box.BoxChild w28 = ((global::Gtk.Box.BoxChild)(this.hbox10[this.BS]));
		w28.Position = 1;
		w28.Expand = false;
		w28.Fill = false;
		this.hbox1.Add(this.hbox10);
		global::Gtk.Box.BoxChild w29 = ((global::Gtk.Box.BoxChild)(this.hbox1[this.hbox10]));
		w29.Position = 2;
		w29.Expand = false;
		w29.Fill = false;
		this.vbox2.Add(this.hbox1);
		global::Gtk.Box.BoxChild w30 = ((global::Gtk.Box.BoxChild)(this.vbox2[this.hbox1]));
		w30.Position = 2;
		w30.Expand = false;
		w30.Fill = false;
		this.vbox1.Add(this.vbox2);
		global::Gtk.Box.BoxChild w31 = ((global::Gtk.Box.BoxChild)(this.vbox1[this.vbox2]));
		w31.Position = 2;
		w31.Expand = false;
		w31.Fill = false;
		this.Add(this.vbox1);
		if ((this.Child != null))
		{
			this.Child.ShowAll();
		}
		this.DefaultWidth = 214;
		this.DefaultHeight = 316;
		this.Show();
		this.DeleteEvent += new global::Gtk.DeleteEventHandler(this.OnDeleteEvent);
		this.Bvaciar.Clicked += new global::System.EventHandler(this.OnBvaciarClicked);
		this.BC.Clicked += new global::System.EventHandler(this.OnBCClicked);
		this.BP.Clicked += new global::System.EventHandler(this.OnBPClicked);
		this.BCero.Clicked += new global::System.EventHandler(this.OnBCeroClicked);
		this.BI.Clicked += new global::System.EventHandler(this.OnBIClicked);
		this.BR.Clicked += new global::System.EventHandler(this.OnBRClicked);
		this.B7.Clicked += new global::System.EventHandler(this.OnB7Clicked);
		this.B8.Clicked += new global::System.EventHandler(this.OnB8Clicked);
		this.B9.Clicked += new global::System.EventHandler(this.OnB9Clicked);
		this.BD.Clicked += new global::System.EventHandler(this.OnBDClicked);
		this.B4.Clicked += new global::System.EventHandler(this.OnB4Clicked);
		this.B5.Clicked += new global::System.EventHandler(this.OnB5Clicked);
		this.B6.Clicked += new global::System.EventHandler(this.OnB6Clicked);
		this.BM.Clicked += new global::System.EventHandler(this.OnBMClicked);
		this.B1.Clicked += new global::System.EventHandler(this.OnB1Clicked);
		this.B2.Clicked += new global::System.EventHandler(this.OnB2Clicked);
		this.B3.Clicked += new global::System.EventHandler(this.OnB3Clicked);
		this.BS.Clicked += new global::System.EventHandler(this.OnBSClicked);
	}
}
